export type FallerItem = { glyph: string; kind?: "emoji" | "text" };

export const FALLER_POOLS = {
  hero: [
    { glyph: "★", kind: "text" },
    { glyph: "⭐" },
    { glyph: "✦", kind: "text" },
    { glyph: "✨" },
  ],
  pillars: [
    { glyph: "★", kind: "text" },
    { glyph: "⭐" },
    { glyph: "🎯" },
    { glyph: "✨" },
    { glyph: "🎰" },
  ],
  features: [
    { glyph: "📱" },
    { glyph: "▦", kind: "text" },
    { glyph: "🎰" },
    { glyph: "🍔" },
    { glyph: "🔑" },
    { glyph: "★", kind: "text" },
  ],
  visits: [
    { glyph: "G", kind: "text" },
    { glyph: "◎", kind: "text" },
    { glyph: "♪", kind: "text" },
    { glyph: "★", kind: "text" },
    { glyph: "⭐" },
  ],
  advantages: [
    { glyph: "🎮" },
    { glyph: "🏆" },
    { glyph: "★", kind: "text" },
    { glyph: "✨" },
  ],
  pricing: [
    { glyph: "☕" },
    { glyph: "✂️" },
    { glyph: "💈" },
    { glyph: "🍔" },
    { glyph: "🔑" },
    { glyph: "🍕" },
    { glyph: "★", kind: "text" },
    { glyph: "⭐" },
  ],
  faq: [
    { glyph: "☕" },
    { glyph: "✂️" },
    { glyph: "💈" },
    { glyph: "🍔" },
    { glyph: "🔑" },
    { glyph: "★", kind: "text" },
    { glyph: "⭐" },
    { glyph: "🍕" },
    { glyph: "🔔" },
    { glyph: "🎁" },
  ],
} as const satisfies Record<string, FallerItem[]>;
